version: '3.8'

services:
  angular-app:
    build: .
    container_name: angular-app
    ports:
      - "4200:4200"
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./.npm-cache:/app/.npm-cache
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096 